"""Canonical signal models for the trading bot.

Signal represents a trading intent generated by a strategy. SignalDirection
indicates whether the signal is to go long, short, or close an existing position.

All modules that need Signal or SignalDirection should import from here.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from decimal import Decimal
from enum import Enum
from typing import Any


class SignalDirection(Enum):
    """Direction of a trading signal."""

    LONG = "LONG"
    SHORT = "SHORT"
    CLOSE = "CLOSE"


class OrderType(Enum):
    """Supported order types for IBKR submission."""

    MARKET = "MKT"
    LIMIT = "LMT"
    STOP = "STP"
    STOP_LIMIT = "STP LMT"
    TRAILING_STOP = "TRAIL"
    BRACKET = "BRACKET"


@dataclass
class Signal:
    """Trading signal generated by a strategy.

    Attributes:
        strategy_name: Name of the strategy that generated this signal.
        symbol: Ticker symbol for the instrument.
        direction: LONG, SHORT, or CLOSE.
        confidence: Confidence level from 0.0 to 1.0.
        suggested_size: Suggested position size in dollars.
        order_type: Type of order to place.
        limit_price: Limit price for limit/stop-limit orders.
        stop_price: Stop price for stop/stop-limit/trailing orders.
        metadata: Arbitrary strategy-specific metadata.
        timestamp: When the signal was generated (UTC).
    """

    strategy_name: str
    symbol: str
    direction: SignalDirection
    confidence: float
    suggested_size: Decimal
    order_type: OrderType
    limit_price: Decimal | None = None
    stop_price: Decimal | None = None
    metadata: dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
