"""Canonical signal models for the trading bot.

Signal represents a trading intent generated by a strategy. SignalDirection
indicates whether the signal is to go long, short, or close an existing position.

All modules that need Signal or SignalDirection should import from here.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, date, datetime
from decimal import Decimal
from enum import Enum
from typing import Any


class SignalDirection(Enum):
    """Direction of a trading signal."""

    LONG = "LONG"
    SHORT = "SHORT"
    CLOSE = "CLOSE"


class OrderType(Enum):
    """Supported order types for IBKR submission."""

    MARKET = "MKT"
    LIMIT = "LMT"
    STOP = "STP"
    STOP_LIMIT = "STP LMT"
    TRAILING_STOP = "TRAIL"
    BRACKET = "BRACKET"


@dataclass
class OptionSignalParams:
    """Parameters specific to options signals.

    Carries the information needed to build an ib_async Option contract
    from a trading signal.

    Attributes:
        underlying: The underlying ticker symbol (e.g. "AAPL").
        strike: The option strike price.
        expiration: The option expiration date.
        right: "P" for put, "C" for call.
        action: The options action (e.g. "SELL_TO_OPEN", "BUY_TO_CLOSE").
    """

    underlying: str
    strike: Decimal
    expiration: date
    right: str  # "P" or "C"
    action: str  # "SELL_TO_OPEN", "BUY_TO_CLOSE"


@dataclass
class Signal:
    """Trading signal generated by a strategy.

    Attributes:
        strategy_name: Name of the strategy that generated this signal.
        symbol: Ticker symbol for the instrument.
        direction: LONG, SHORT, or CLOSE.
        confidence: Confidence level from 0.0 to 1.0.
        suggested_size: Suggested position size in dollars.
        order_type: Type of order to place.
        limit_price: Limit price for limit/stop-limit orders.
        stop_price: Stop price for stop/stop-limit/trailing orders.
        metadata: Arbitrary strategy-specific metadata.
        timestamp: When the signal was generated (UTC).
    """

    strategy_name: str
    symbol: str
    direction: SignalDirection
    confidence: float
    suggested_size: Decimal
    order_type: OrderType
    limit_price: Decimal | None = None
    stop_price: Decimal | None = None
    metadata: dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=lambda: datetime.now(UTC))
    option_params: OptionSignalParams | None = None
